### ISSUE TITLE
bug: app crashes if the node is not up or if the provided ln socket path is not correct.

### ISSUE THREAD

**Issue by Harshit933** [dart-lightning/lndart.clnapp#101]
Screenshot for the error: 

![image](https://github.com/dart-lightning/lndart.clnapp/assets/90508384/77657f62-cb3f-44dd-8ca7-344f2fecc148)

**Comment by vincenzopalazzo** [comment]
Good catch should be fixed in https://github.com/dart-lightning/lndart.clnapp/issues/89
