### ISSUE TITLE
Unhandled unix socket exception

### ISSUE THREAD

**Issue by Harshit933** [dart-lightning/lndart.clnapp#123]
Reference https://github.com/dart-lightning/lndart.clnapp/pull/116#discussion_r1267975704

**Comment by vincenzopalazzo** [comment]
This can be solved in https://github.com/dart-lightning/lndart.clnapp/pull/122/files by fixing the cln.cln library

**Comment by vincenzopalazzo** [comment]
Please can you confirm that this issue is fixed? @Harshit933 

If you enter a wrong bolt11 and pay it, what do you get?

**Comment by Harshit933** [comment]
Yes it is fixed. We are getting this : 

![image](https://github.com/dart-lightning/lndart.clnapp/assets/90508384/381a5c58-7169-48c4-b923-08992fba8f33)

**Comment by vincenzopalazzo** [comment]
Nice!
