### ISSUE TITLE
tot amount in the home view should take into count also the invoice

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#132]
OK when the invoice does not have an amount, and the user will send any amount inside the payment the app loses this payment

![signal-2023-07-24-142651_002](https://github.com/dart-lightning/lndart.clnapp/assets/17150045/3d928d9d-fb41-4055-9234-09d5549713f8)

**Comment by Harshit933** [comment]
This was fixed in #136
