### ISSUE TITLE
ui: the list view of the payment can contain a expandible card 

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#17]
The work in this PR is good https://github.com/dart-lightning/lndart.clnapp/pull/16 but the item can be an expandable card like the one used in the https://lnmetrics.info

You find an example in the [trash](https://github.com/vincenzopalazzo/trash) package

**Comment by believeInJha** [comment]
Hi, @vincenzopalazzo Can you assign me this issue? I want to participate in the summer of bitcoin!!

**Comment by believeInJha** [comment]
Hi @vincenzopalazzo @KAVAN-DESAI, I have a doubt. Do I have to set up a lightning node for the settings page or do you guys have test credentials for Node ID, Host, Lamda Server & Rune?

**Comment by vincenzopalazzo** [comment]
@believeInJha you can use the Unix RPC socket of core lighting, but for sure you must run a lightning node

**Comment by Ram-lankada** [comment]
Hi @vincenzopalazzo , please assign this to me. I'll get the work done.
