### ISSUE TITLE
track field of amount of msat in invoice

### ISSUE THREAD

**Issue by KAVAN-DESAI** [dart-lightning/lndart.clnapp#24]
listinvoice contains amount of msat field which is a string in Core Lightning, which can be changed in future to int 
```dart
final String amount;
```

**Comment by vincenzopalazzo** [comment]
Relate to https://github.com/ElementsProject/lightning/pull/5306

**Comment by KAVAN-DESAI** [comment]
fix: [a138caf](https://github.com/dart-lightning/lndart.clnapp/pull/40/commits/a138caf96b4108c461c090e12947fbccc0af9562)
