### ISSUE TITLE
use listpays instead of listinvoices in the home view

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#28]
List invoices did not contain the payments that we did or received with the node, but the listpays does.

In addition, payment can decrease or increase the actual capacity of the node and this is something that we can calculate with the node id contained inside the from the field of the `listpays` command

**Comment by Harshit933** [comment]
Hey, I would like to work on this issue, I am quite proficient in dart and would love to give it a try!

**Comment by vincenzopalazzo** [comment]
>Hey, I would like to work on this issue, I am quite proficient in dart and would love to give it a try!

Go for it, but this required to run core lightning and playing a little bit, ping me if you want to open a channel with my testnet node

**Comment by vincenzopalazzo** [comment]
@Harshit933 separate class yes, but also separate files, I think we should add all the setting class inside a `settings` folder
