### ISSUE TITLE
setting: I clear the settings and I restart the app but I get an error that the API is already register

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#43]
Maybe this is caused by the https://github.com/dart-lightning/lndart.clnapp/pull/35#discussion_r944686836

**Comment by KAVAN-DESAI** [comment]
fixed [ef8d3eb](https://github.com/dart-lightning/lndart.clnapp/pull/35/commits/ef8d3ebb8854f6042623e5700734489a37c46606)
