### ISSUE TITLE
split the setting view in different view

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#45]
## Problem

Our Setting View is not showing a very nice UI because is developed in the wrong way!

## Backgbround

This task required reworking the Setting View by splitting the sub-view in different Widget as suggested in this issue https://github.com/dart-lightning/lndart.clnapp/pull/35#discussion_r944285954

## Goal

Make the setting view code clean to read and also easy to work on it

## Object of this tasks

- Show that you are able to understand how Flutter works, and not just make some code that works
- Show that you are able to work with git, and follow the contributor guideline https://github.com/dart-lightning/lndart.clnapp/blob/main/docs/dev/MAINTAINERS.md
- Show that you can propose and improve the application with your own idea from a general one

**Comment by Harshit933** [comment]
Please assign me to this issue.

**Comment by vincenzopalazzo** [comment]
>Please assign me to this issue.

Done, please consider to test also the solution that you provide with core lightning up and running

**Comment by Harshit933** [comment]
For sure! also can you provide me some documentation on what are the node id, host, lambda server and rune are?

**Comment by vincenzopalazzo** [comment]
>For sure! also can you provide me some documentation on what are the node id, host, lambda server and rune are?

I should provide this information, sorry about that! But this required a little bit of background on core lightning, maybe you can run the desktop version of the app, and use the UNIX socket? The UNIX socket path is `.lightning/testnet`

**Comment by Harshit933** [comment]
> I should provide this information, sorry about that! But this required a little bit of background on core lightning, maybe you can run the desktop version of the app, and use the UNIX socket? The UNIX socket path is `.lightning/testnet`

How do I communicate with the socket? I haven't worked with sockets till now.

**Comment by vincenzopalazzo** [comment]
for the use case that I described we use https://github.com/dart-lightning/lndart.cln but the app already use it.

You use the socket :) with HTTP requests, the cln socket is just a special one that is inside the `.lightning/testnet/lightning-rpc` as all in linux is just a file

**Comment by Harshit933** [comment]
I only have `.config` file inside the `.lightning/testnet/`
