### ISSUE TITLE
Implement basic request view for generating inovice

### ISSUE THREAD

**Issue by KAVAN-DESAI** [dart-lightning/lndart.clnapp#67]
# Background

The application now is not able to show to generate a request payment (aka bolt 11), so this mini project is using the current architecture to propose a workable solution that allow to form the following use case

1 Required an invoice with the following command https://lightning.readthedocs.io/lightning-invoice.7.html 
    1.1 Required all the required input from the user in a well defined UI
    1.2 Make the request to core lightning, and get back the response
    1.3 show the response in a QRCode by using the following package https://github.com/theyakka/qr.flutter

# Goal

Implement basic screen which takes useful inputs to generate invoice. Primiraly there are 3 input fields `amount_msat, label, description`. Feel free to checkout docs and add more optional fields(https://lightning.readthedocs.io/lightning-invoice.7.html)

After the user enters all the 3 fields and requests to generate an Invoice a QR code should be displayed.

I am hereby attaching some raw UI for the requested view reference

![image](https://user-images.githubusercontent.com/62831469/192549971-74e62c33-6e7b-45f7-9622-29234e1de710.png)

![image](https://user-images.githubusercontent.com/62831469/192576487-0d690215-e939-4ad9-8763-e79bbae34aa5.png)

![image](https://bitcoin.design/assets/images/guide/daily-spending-wallet/requesting/Invoice@2x.png)

## End Goal

The final goal of this project is to be able to require from a remote node invoice and show it to the screen, and the solution needs to be workable and a well-developed solution following all the standards of flutter that need to work on all the platforms

**Comment by vincenzopalazzo** [comment]
Fixed https://github.com/dart-lightning/lndart.clnapp/pull/110
