### ISSUE TITLE
fix the flutter widget in order to display the Setting view

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#71]
## Problem

Our Setting View is not showing a very nice UI because is developed in the wrong way!

## Backgbround

This task required reworking the Setting View by wrapping the UI inside a [SafeArea](https://api.flutter.dev/flutter/widgets/SafeArea-class.html) and building the component with the Row/Colum + [Expanded](https://api.flutter.dev/flutter/widgets/Expanded-class.html) or [Flexible](https://api.flutter.dev/flutter/widgets/Flexible-class.html)

![view01](https://user-images.githubusercontent.com/17150045/220177368-4514ff09-4dd5-4475-8cb4-cd60300e93ef.png)

## Goal

Make the setting view responsive and nicer to use.

## Object of this tasks

- Show that you are able to understand how Flutter, and not just make some code that works
- Show that you are able to work with git, and follow the contributor guideline https://github.com/dart-lightning/lndart.clnapp/blob/main/docs/dev/MAINTAINERS.md
- Show that you can propose and improve the application with your own idea from a general one

**Comment by Shikhar12233456** [comment]
@vincenzopalazzo  please assign this issue to me.
