### ISSUE TITLE
Feature Request [Developement ]: No issue and PR template in repository 

### ISSUE THREAD

**Issue by SiddheshKukade** [dart-lightning/lndart.clnapp#72]
#### Solution: 
- We can add a `issue template` in the `.github/ISSUE_TEMPLATE/` folder and `.github/PULL_REQUEST_TEMPLATE/`
- [This article explains benefits of Issues and Pull Request templates ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests)
- GitHub also suggests to use templates for issues 
![image](https://user-images.githubusercontent.com/65951872/221550504-d148f895-556f-4cd2-b1e3-b7109f303562.png)

**Comment by vincenzopalazzo** [comment]
I agree but this is useful when you had a functional APP, and this is still in development maybe later when we had something that works

**Comment by SiddheshKukade** [comment]
@vincenzopalazzo Sir I've previously contributed and added templates to other popular open source projects as well.
Some of them are Linked below;
[Palisadoes Foundation: ](https://github.com/PalisadoesFoundation)
https://github.com/PalisadoesFoundation/talawa-docs/issues/237
https://github.com/PalisadoesFoundation/talawa-docs/pull/238

[Pastme Python library:](https://github.com/collove/pasteme/)
https://github.com/collove/pasteme/issues/26
https://github.com/collove/pasteme/pull/30

**Comment by SiddheshKukade** [comment]
Sir, can I work on this ? I would like to get assigned.

**Comment by vincenzopalazzo** [comment]
PRs are welcome but I do not think I will get merger soonish due to this https://github.com/dart-lightning/lndart.clnapp/issues/72#issuecomment-1446157189

And this will not be included in the **pre-SoB**

**Comment by SiddheshKukade** [comment]
@vincenzopalazzo Sir, I've created a PR https://github.com/dart-lightning/lndart.clnapp/pull/73  to fix this and I've also attached the preview screenshots, feel free to merge when the app is ready. 
Also feel free to ping me @SiddheshKukade  in the future If there were any improvement to be made for this.
I will be available, thanks.
