### ISSUE TITLE
bug : getDirectoryPath() was'nt implemented for Chrome CLNAPP. 

### ISSUE THREAD

**Issue by Ram-lankada** [dart-lightning/lndart.clnapp#83]
When trying to connect CLNAPP to ln node via "gRPC client" / "unixSocket client" file explorer isn't getting opened on clicking browse button. 

therefore unable to connect the ln node with CLNAPP. 

![getDirectory()](https://user-images.githubusercontent.com/91232198/226115763-7ae3e6f5-81b1-4e14-8b57-2a74f838d140.png)

**Comment by vincenzopalazzo** [comment]
chrome or equal has no access to the disk this is true in any languages unfortunatly
